/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PreviewLiveActivityRouteImport } from './routes/preview-live-activity'
import { Route as PreviewQuestCardsRouteImport } from './routes/preview-quest-cards'
import { Route as PreviewReferRouteImport } from './routes/preview-refer'
import { Route as PreviewReferralRulesRouteImport } from './routes/preview-referral-rules'
import { Route as PreviewSectionHeadingRouteImport } from './routes/preview-section-heading'
import { Route as PreviewSplashRouteImport } from './routes/preview-splash'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFeaturedRouteImport } from './routes/_authenticated/featured'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMySubmissionsRouteImport } from './routes/_authenticated/my-submissions'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedOfferwallRouteImport } from './routes/_authenticated/offerwall'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated/refer'
import { Route as AuthenticatedReferralRulesRouteImport } from './routes/_authenticated/referral-rules'
import { Route as AuthenticatedSpecialRouteImport } from './routes/_authenticated/special'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTaskRouteImport } from './routes/_authenticated/task'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthConfirmedRouteImport } from './routes/auth_.confirmed'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalReferralTermsRouteImport } from './routes/legal/referral-terms'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalWithdrawalPolicyRouteImport } from './routes/legal/withdrawal-policy'
import { Route as AuthenticatedAdvertiserCampaignsRouteImport } from './routes/_authenticated/advertiser/campaigns'
import { Route as AuthenticatedAdvertiserCreateRouteImport } from './routes/_authenticated/advertiser/create'
import { Route as AuthenticatedAdvertiserFundsRouteImport } from './routes/_authenticated/advertiser/funds'
import { Route as AuthenticatedAdvertiserHelpRouteImport } from './routes/_authenticated/advertiser/help'
import { Route as AuthenticatedAdvertiserReferralRouteImport } from './routes/_authenticated/advertiser/referral'
import { Route as AuthenticatedAdvertiserTransactionsRouteImport } from './routes/_authenticated/advertiser/transactions'
import { Route as AuthenticatedMicrotaskProofIdRouteImport } from './routes/_authenticated/microtask-proof.$id'
import { Route as AuthenticatedMicrotaskIdRouteImport } from './routes/_authenticated/microtask.$id'
import { Route as ApiCronRefreshOfferFeedRouteImport } from './routes/api/cron/refresh-offer-feed'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as AuthenticatedAdvertiserResultsIdRouteImport } from './routes/_authenticated/advertiser/results.$id'
import { Route as AuthenticatedGoQuestKeyStepRouteImport } from './routes/_authenticated/go.$questKey.$step'
import { Route as AuthenticatedGoLockerReturnRouteImport } from './routes/_authenticated/go.locker.return'
import { Route as ApiPublicOfferPostbackOfferIdRouteImport } from './routes/api/public/offer-postback.$offerId'
import { Route as ApiPublicOfferwallSlugRouteImport } from './routes/api/public/offerwall/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewLiveActivityRoute = PreviewLiveActivityRouteImport.update({
  id: '/preview-live-activity',
  path: '/preview-live-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewQuestCardsRoute = PreviewQuestCardsRouteImport.update({
  id: '/preview-quest-cards',
  path: '/preview-quest-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewReferRoute = PreviewReferRouteImport.update({
  id: '/preview-refer',
  path: '/preview-refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewReferralRulesRoute = PreviewReferralRulesRouteImport.update({
  id: '/preview-referral-rules',
  path: '/preview-referral-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSectionHeadingRoute = PreviewSectionHeadingRouteImport.update({
  id: '/preview-section-heading',
  path: '/preview-section-heading',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewSplashRoute = PreviewSplashRouteImport.update({
  id: '/preview-splash',
  path: '/preview-splash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeaturedRoute = AuthenticatedFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySubmissionsRoute =
  AuthenticatedMySubmissionsRouteImport.update({
    id: '/my-submissions',
    path: '/my-submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfferwallRoute = AuthenticatedOfferwallRouteImport.update({
  id: '/offerwall',
  path: '/offerwall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRulesRoute =
  AuthenticatedReferralRulesRouteImport.update({
    id: '/referral-rules',
    path: '/referral-rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpecialRoute = AuthenticatedSpecialRouteImport.update({
  id: '/special',
  path: '/special',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskRoute = AuthenticatedTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthConfirmedRoute = AuthConfirmedRouteImport.update({
  id: '/auth_/confirmed',
  path: '/auth/confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReferralTermsRoute = LegalReferralTermsRouteImport.update({
  id: '/legal/referral-terms',
  path: '/legal/referral-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalWithdrawalPolicyRoute = LegalWithdrawalPolicyRouteImport.update({
  id: '/legal/withdrawal-policy',
  path: '/legal/withdrawal-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdvertiserCampaignsRoute =
  AuthenticatedAdvertiserCampaignsRouteImport.update({
    id: '/advertiser/campaigns',
    path: '/advertiser/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvertiserCreateRoute =
  AuthenticatedAdvertiserCreateRouteImport.update({
    id: '/advertiser/create',
    path: '/advertiser/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvertiserFundsRoute =
  AuthenticatedAdvertiserFundsRouteImport.update({
    id: '/advertiser/funds',
    path: '/advertiser/funds',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvertiserHelpRoute =
  AuthenticatedAdvertiserHelpRouteImport.update({
    id: '/advertiser/help',
    path: '/advertiser/help',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvertiserReferralRoute =
  AuthenticatedAdvertiserReferralRouteImport.update({
    id: '/advertiser/referral',
    path: '/advertiser/referral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdvertiserTransactionsRoute =
  AuthenticatedAdvertiserTransactionsRouteImport.update({
    id: '/advertiser/transactions',
    path: '/advertiser/transactions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMicrotaskProofIdRoute =
  AuthenticatedMicrotaskProofIdRouteImport.update({
    id: '/microtask-proof/$id',
    path: '/microtask-proof/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMicrotaskIdRoute =
  AuthenticatedMicrotaskIdRouteImport.update({
    id: '/microtask/$id',
    path: '/microtask/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiCronRefreshOfferFeedRoute = ApiCronRefreshOfferFeedRouteImport.update({
  id: '/api/cron/refresh-offer-feed',
  path: '/api/cron/refresh-offer-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdvertiserResultsIdRoute =
  AuthenticatedAdvertiserResultsIdRouteImport.update({
    id: '/advertiser/results/$id',
    path: '/advertiser/results/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoQuestKeyStepRoute =
  AuthenticatedGoQuestKeyStepRouteImport.update({
    id: '/go/$questKey/$step',
    path: '/go/$questKey/$step',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoLockerReturnRoute =
  AuthenticatedGoLockerReturnRouteImport.update({
    id: '/go/locker/return',
    path: '/go/locker/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOfferPostbackOfferIdRoute =
  ApiPublicOfferPostbackOfferIdRouteImport.update({
    id: '/api/public/offer-postback/$offerId',
    path: '/api/public/offer-postback/$offerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOfferwallSlugRoute = ApiPublicOfferwallSlugRouteImport.update({
  id: '/api/public/offerwall/$slug',
  path: '/api/public/offerwall/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/preview-live-activity': typeof PreviewLiveActivityRoute
  '/preview-quest-cards': typeof PreviewQuestCardsRoute
  '/preview-refer': typeof PreviewReferRoute
  '/preview-referral-rules': typeof PreviewReferralRulesRoute
  '/preview-section-heading': typeof PreviewSectionHeadingRoute
  '/preview-splash': typeof PreviewSplashRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-submissions': typeof AuthenticatedMySubmissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/offerwall': typeof AuthenticatedOfferwallRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/referral-rules': typeof AuthenticatedReferralRulesRoute
  '/special': typeof AuthenticatedSpecialRoute
  '/support': typeof AuthenticatedSupportRoute
  '/task': typeof AuthenticatedTaskRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/advertiser/campaigns': typeof AuthenticatedAdvertiserCampaignsRoute
  '/advertiser/create': typeof AuthenticatedAdvertiserCreateRoute
  '/advertiser/funds': typeof AuthenticatedAdvertiserFundsRoute
  '/advertiser/help': typeof AuthenticatedAdvertiserHelpRoute
  '/advertiser/referral': typeof AuthenticatedAdvertiserReferralRoute
  '/advertiser/transactions': typeof AuthenticatedAdvertiserTransactionsRoute
  '/microtask-proof/$id': typeof AuthenticatedMicrotaskProofIdRoute
  '/microtask/$id': typeof AuthenticatedMicrotaskIdRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/advertiser/results/$id': typeof AuthenticatedAdvertiserResultsIdRoute
  '/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/go/locker/return': typeof AuthenticatedGoLockerReturnRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/preview-live-activity': typeof PreviewLiveActivityRoute
  '/preview-quest-cards': typeof PreviewQuestCardsRoute
  '/preview-refer': typeof PreviewReferRoute
  '/preview-referral-rules': typeof PreviewReferralRulesRoute
  '/preview-section-heading': typeof PreviewSectionHeadingRoute
  '/preview-splash': typeof PreviewSplashRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/my-submissions': typeof AuthenticatedMySubmissionsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/offerwall': typeof AuthenticatedOfferwallRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/referral-rules': typeof AuthenticatedReferralRulesRoute
  '/special': typeof AuthenticatedSpecialRoute
  '/support': typeof AuthenticatedSupportRoute
  '/task': typeof AuthenticatedTaskRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/auth/confirmed': typeof AuthConfirmedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/advertiser/campaigns': typeof AuthenticatedAdvertiserCampaignsRoute
  '/advertiser/create': typeof AuthenticatedAdvertiserCreateRoute
  '/advertiser/funds': typeof AuthenticatedAdvertiserFundsRoute
  '/advertiser/help': typeof AuthenticatedAdvertiserHelpRoute
  '/advertiser/referral': typeof AuthenticatedAdvertiserReferralRoute
  '/advertiser/transactions': typeof AuthenticatedAdvertiserTransactionsRoute
  '/microtask-proof/$id': typeof AuthenticatedMicrotaskProofIdRoute
  '/microtask/$id': typeof AuthenticatedMicrotaskIdRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/advertiser/results/$id': typeof AuthenticatedAdvertiserResultsIdRoute
  '/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/go/locker/return': typeof AuthenticatedGoLockerReturnRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/preview-live-activity': typeof PreviewLiveActivityRoute
  '/preview-quest-cards': typeof PreviewQuestCardsRoute
  '/preview-refer': typeof PreviewReferRoute
  '/preview-referral-rules': typeof PreviewReferralRulesRoute
  '/preview-section-heading': typeof PreviewSectionHeadingRoute
  '/preview-splash': typeof PreviewSplashRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/featured': typeof AuthenticatedFeaturedRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/my-submissions': typeof AuthenticatedMySubmissionsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/offerwall': typeof AuthenticatedOfferwallRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/_authenticated/referral-rules': typeof AuthenticatedReferralRulesRoute
  '/_authenticated/special': typeof AuthenticatedSpecialRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/task': typeof AuthenticatedTaskRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/auth_/confirmed': typeof AuthConfirmedRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/_authenticated/advertiser/campaigns': typeof AuthenticatedAdvertiserCampaignsRoute
  '/_authenticated/advertiser/create': typeof AuthenticatedAdvertiserCreateRoute
  '/_authenticated/advertiser/funds': typeof AuthenticatedAdvertiserFundsRoute
  '/_authenticated/advertiser/help': typeof AuthenticatedAdvertiserHelpRoute
  '/_authenticated/advertiser/referral': typeof AuthenticatedAdvertiserReferralRoute
  '/_authenticated/advertiser/transactions': typeof AuthenticatedAdvertiserTransactionsRoute
  '/_authenticated/microtask-proof/$id': typeof AuthenticatedMicrotaskProofIdRoute
  '/_authenticated/microtask/$id': typeof AuthenticatedMicrotaskIdRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/_authenticated/advertiser/results/$id': typeof AuthenticatedAdvertiserResultsIdRoute
  '/_authenticated/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/_authenticated/go/locker/return': typeof AuthenticatedGoLockerReturnRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/preview-live-activity'
    | '/preview-quest-cards'
    | '/preview-refer'
    | '/preview-referral-rules'
    | '/preview-section-heading'
    | '/preview-splash'
    | '/admin'
    | '/featured'
    | '/home'
    | '/my-submissions'
    | '/notifications'
    | '/offers'
    | '/offerwall'
    | '/onboarding'
    | '/profile'
    | '/refer'
    | '/referral-rules'
    | '/special'
    | '/support'
    | '/task'
    | '/wallet'
    | '/auth/confirmed'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/advertiser/campaigns'
    | '/advertiser/create'
    | '/advertiser/funds'
    | '/advertiser/help'
    | '/advertiser/referral'
    | '/advertiser/transactions'
    | '/microtask-proof/$id'
    | '/microtask/$id'
    | '/api/cron/refresh-offer-feed'
    | '/api/public/razorpay-webhook'
    | '/advertiser/results/$id'
    | '/go/$questKey/$step'
    | '/go/locker/return'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/preview-live-activity'
    | '/preview-quest-cards'
    | '/preview-refer'
    | '/preview-referral-rules'
    | '/preview-section-heading'
    | '/preview-splash'
    | '/admin'
    | '/featured'
    | '/home'
    | '/my-submissions'
    | '/notifications'
    | '/offers'
    | '/offerwall'
    | '/onboarding'
    | '/profile'
    | '/refer'
    | '/referral-rules'
    | '/special'
    | '/support'
    | '/task'
    | '/wallet'
    | '/auth/confirmed'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/advertiser/campaigns'
    | '/advertiser/create'
    | '/advertiser/funds'
    | '/advertiser/help'
    | '/advertiser/referral'
    | '/advertiser/transactions'
    | '/microtask-proof/$id'
    | '/microtask/$id'
    | '/api/cron/refresh-offer-feed'
    | '/api/public/razorpay-webhook'
    | '/advertiser/results/$id'
    | '/go/$questKey/$step'
    | '/go/locker/return'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/preview-live-activity'
    | '/preview-quest-cards'
    | '/preview-refer'
    | '/preview-referral-rules'
    | '/preview-section-heading'
    | '/preview-splash'
    | '/_authenticated/admin'
    | '/_authenticated/featured'
    | '/_authenticated/home'
    | '/_authenticated/my-submissions'
    | '/_authenticated/notifications'
    | '/_authenticated/offers'
    | '/_authenticated/offerwall'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/refer'
    | '/_authenticated/referral-rules'
    | '/_authenticated/special'
    | '/_authenticated/support'
    | '/_authenticated/task'
    | '/_authenticated/wallet'
    | '/auth_/confirmed'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/_authenticated/advertiser/campaigns'
    | '/_authenticated/advertiser/create'
    | '/_authenticated/advertiser/funds'
    | '/_authenticated/advertiser/help'
    | '/_authenticated/advertiser/referral'
    | '/_authenticated/advertiser/transactions'
    | '/_authenticated/microtask-proof/$id'
    | '/_authenticated/microtask/$id'
    | '/api/cron/refresh-offer-feed'
    | '/api/public/razorpay-webhook'
    | '/_authenticated/advertiser/results/$id'
    | '/_authenticated/go/$questKey/$step'
    | '/_authenticated/go/locker/return'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  PreviewLiveActivityRoute: typeof PreviewLiveActivityRoute
  PreviewQuestCardsRoute: typeof PreviewQuestCardsRoute
  PreviewReferRoute: typeof PreviewReferRoute
  PreviewReferralRulesRoute: typeof PreviewReferralRulesRoute
  PreviewSectionHeadingRoute: typeof PreviewSectionHeadingRoute
  PreviewSplashRoute: typeof PreviewSplashRoute
  AuthConfirmedRoute: typeof AuthConfirmedRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalReferralTermsRoute: typeof LegalReferralTermsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalWithdrawalPolicyRoute: typeof LegalWithdrawalPolicyRoute
  ApiCronRefreshOfferFeedRoute: typeof ApiCronRefreshOfferFeedRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicOfferPostbackOfferIdRoute: typeof ApiPublicOfferPostbackOfferIdRoute
  ApiPublicOfferwallSlugRoute: typeof ApiPublicOfferwallSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-live-activity': {
      id: '/preview-live-activity'
      path: '/preview-live-activity'
      fullPath: '/preview-live-activity'
      preLoaderRoute: typeof PreviewLiveActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-quest-cards': {
      id: '/preview-quest-cards'
      path: '/preview-quest-cards'
      fullPath: '/preview-quest-cards'
      preLoaderRoute: typeof PreviewQuestCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-refer': {
      id: '/preview-refer'
      path: '/preview-refer'
      fullPath: '/preview-refer'
      preLoaderRoute: typeof PreviewReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-referral-rules': {
      id: '/preview-referral-rules'
      path: '/preview-referral-rules'
      fullPath: '/preview-referral-rules'
      preLoaderRoute: typeof PreviewReferralRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-section-heading': {
      id: '/preview-section-heading'
      path: '/preview-section-heading'
      fullPath: '/preview-section-heading'
      preLoaderRoute: typeof PreviewSectionHeadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-splash': {
      id: '/preview-splash'
      path: '/preview-splash'
      fullPath: '/preview-splash'
      preLoaderRoute: typeof PreviewSplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/featured': {
      id: '/_authenticated/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof AuthenticatedFeaturedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-submissions': {
      id: '/_authenticated/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof AuthenticatedMySubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offerwall': {
      id: '/_authenticated/offerwall'
      path: '/offerwall'
      fullPath: '/offerwall'
      preLoaderRoute: typeof AuthenticatedOfferwallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral-rules': {
      id: '/_authenticated/referral-rules'
      path: '/referral-rules'
      fullPath: '/referral-rules'
      preLoaderRoute: typeof AuthenticatedReferralRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/special': {
      id: '/_authenticated/special'
      path: '/special'
      fullPath: '/special'
      preLoaderRoute: typeof AuthenticatedSpecialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task': {
      id: '/_authenticated/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof AuthenticatedTaskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/confirmed': {
      id: '/auth_/confirmed'
      path: '/auth/confirmed'
      fullPath: '/auth/confirmed'
      preLoaderRoute: typeof AuthConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/referral-terms': {
      id: '/legal/referral-terms'
      path: '/legal/referral-terms'
      fullPath: '/legal/referral-terms'
      preLoaderRoute: typeof LegalReferralTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/withdrawal-policy': {
      id: '/legal/withdrawal-policy'
      path: '/legal/withdrawal-policy'
      fullPath: '/legal/withdrawal-policy'
      preLoaderRoute: typeof LegalWithdrawalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advertiser/campaigns': {
      id: '/_authenticated/advertiser/campaigns'
      path: '/advertiser/campaigns'
      fullPath: '/advertiser/campaigns'
      preLoaderRoute: typeof AuthenticatedAdvertiserCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advertiser/create': {
      id: '/_authenticated/advertiser/create'
      path: '/advertiser/create'
      fullPath: '/advertiser/create'
      preLoaderRoute: typeof AuthenticatedAdvertiserCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advertiser/funds': {
      id: '/_authenticated/advertiser/funds'
      path: '/advertiser/funds'
      fullPath: '/advertiser/funds'
      preLoaderRoute: typeof AuthenticatedAdvertiserFundsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advertiser/help': {
      id: '/_authenticated/advertiser/help'
      path: '/advertiser/help'
      fullPath: '/advertiser/help'
      preLoaderRoute: typeof AuthenticatedAdvertiserHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advertiser/referral': {
      id: '/_authenticated/advertiser/referral'
      path: '/advertiser/referral'
      fullPath: '/advertiser/referral'
      preLoaderRoute: typeof AuthenticatedAdvertiserReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/advertiser/transactions': {
      id: '/_authenticated/advertiser/transactions'
      path: '/advertiser/transactions'
      fullPath: '/advertiser/transactions'
      preLoaderRoute: typeof AuthenticatedAdvertiserTransactionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/microtask-proof/$id': {
      id: '/_authenticated/microtask-proof/$id'
      path: '/microtask-proof/$id'
      fullPath: '/microtask-proof/$id'
      preLoaderRoute: typeof AuthenticatedMicrotaskProofIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/microtask/$id': {
      id: '/_authenticated/microtask/$id'
      path: '/microtask/$id'
      fullPath: '/microtask/$id'
      preLoaderRoute: typeof AuthenticatedMicrotaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/cron/refresh-offer-feed': {
      id: '/api/cron/refresh-offer-feed'
      path: '/api/cron/refresh-offer-feed'
      fullPath: '/api/cron/refresh-offer-feed'
      preLoaderRoute: typeof ApiCronRefreshOfferFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/advertiser/results/$id': {
      id: '/_authenticated/advertiser/results/$id'
      path: '/advertiser/results/$id'
      fullPath: '/advertiser/results/$id'
      preLoaderRoute: typeof AuthenticatedAdvertiserResultsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/go/$questKey/$step': {
      id: '/_authenticated/go/$questKey/$step'
      path: '/go/$questKey/$step'
      fullPath: '/go/$questKey/$step'
      preLoaderRoute: typeof AuthenticatedGoQuestKeyStepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/go/locker/return': {
      id: '/_authenticated/go/locker/return'
      path: '/go/locker/return'
      fullPath: '/go/locker/return'
      preLoaderRoute: typeof AuthenticatedGoLockerReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/offer-postback/$offerId': {
      id: '/api/public/offer-postback/$offerId'
      path: '/api/public/offer-postback/$offerId'
      fullPath: '/api/public/offer-postback/$offerId'
      preLoaderRoute: typeof ApiPublicOfferPostbackOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offerwall/$slug': {
      id: '/api/public/offerwall/$slug'
      path: '/api/public/offerwall/$slug'
      fullPath: '/api/public/offerwall/$slug'
      preLoaderRoute: typeof ApiPublicOfferwallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFeaturedRoute: typeof AuthenticatedFeaturedRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMySubmissionsRoute: typeof AuthenticatedMySubmissionsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedOfferwallRoute: typeof AuthenticatedOfferwallRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedReferralRulesRoute: typeof AuthenticatedReferralRulesRoute
  AuthenticatedSpecialRoute: typeof AuthenticatedSpecialRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTaskRoute: typeof AuthenticatedTaskRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAdvertiserCampaignsRoute: typeof AuthenticatedAdvertiserCampaignsRoute
  AuthenticatedAdvertiserCreateRoute: typeof AuthenticatedAdvertiserCreateRoute
  AuthenticatedAdvertiserFundsRoute: typeof AuthenticatedAdvertiserFundsRoute
  AuthenticatedAdvertiserHelpRoute: typeof AuthenticatedAdvertiserHelpRoute
  AuthenticatedAdvertiserReferralRoute: typeof AuthenticatedAdvertiserReferralRoute
  AuthenticatedAdvertiserTransactionsRoute: typeof AuthenticatedAdvertiserTransactionsRoute
  AuthenticatedMicrotaskProofIdRoute: typeof AuthenticatedMicrotaskProofIdRoute
  AuthenticatedMicrotaskIdRoute: typeof AuthenticatedMicrotaskIdRoute
  AuthenticatedAdvertiserResultsIdRoute: typeof AuthenticatedAdvertiserResultsIdRoute
  AuthenticatedGoQuestKeyStepRoute: typeof AuthenticatedGoQuestKeyStepRoute
  AuthenticatedGoLockerReturnRoute: typeof AuthenticatedGoLockerReturnRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFeaturedRoute: AuthenticatedFeaturedRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMySubmissionsRoute: AuthenticatedMySubmissionsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedOfferwallRoute: AuthenticatedOfferwallRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedReferralRulesRoute: AuthenticatedReferralRulesRoute,
  AuthenticatedSpecialRoute: AuthenticatedSpecialRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTaskRoute: AuthenticatedTaskRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAdvertiserCampaignsRoute: AuthenticatedAdvertiserCampaignsRoute,
  AuthenticatedAdvertiserCreateRoute: AuthenticatedAdvertiserCreateRoute,
  AuthenticatedAdvertiserFundsRoute: AuthenticatedAdvertiserFundsRoute,
  AuthenticatedAdvertiserHelpRoute: AuthenticatedAdvertiserHelpRoute,
  AuthenticatedAdvertiserReferralRoute: AuthenticatedAdvertiserReferralRoute,
  AuthenticatedAdvertiserTransactionsRoute:
    AuthenticatedAdvertiserTransactionsRoute,
  AuthenticatedMicrotaskProofIdRoute: AuthenticatedMicrotaskProofIdRoute,
  AuthenticatedMicrotaskIdRoute: AuthenticatedMicrotaskIdRoute,
  AuthenticatedAdvertiserResultsIdRoute: AuthenticatedAdvertiserResultsIdRoute,
  AuthenticatedGoQuestKeyStepRoute: AuthenticatedGoQuestKeyStepRoute,
  AuthenticatedGoLockerReturnRoute: AuthenticatedGoLockerReturnRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  PreviewLiveActivityRoute: PreviewLiveActivityRoute,
  PreviewQuestCardsRoute: PreviewQuestCardsRoute,
  PreviewReferRoute: PreviewReferRoute,
  PreviewReferralRulesRoute: PreviewReferralRulesRoute,
  PreviewSectionHeadingRoute: PreviewSectionHeadingRoute,
  PreviewSplashRoute: PreviewSplashRoute,
  AuthConfirmedRoute: AuthConfirmedRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalReferralTermsRoute: LegalReferralTermsRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalWithdrawalPolicyRoute: LegalWithdrawalPolicyRoute,
  ApiCronRefreshOfferFeedRoute: ApiCronRefreshOfferFeedRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicOfferPostbackOfferIdRoute: ApiPublicOfferPostbackOfferIdRoute,
  ApiPublicOfferwallSlugRoute: ApiPublicOfferwallSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
