/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFeaturedRouteImport } from './routes/_authenticated/featured'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOffersRouteImport } from './routes/_authenticated/offers'
import { Route as AuthenticatedOfferwallRouteImport } from './routes/_authenticated/offerwall'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferRouteImport } from './routes/_authenticated/refer'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTaskRouteImport } from './routes/_authenticated/task'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalReferralTermsRouteImport } from './routes/legal/referral-terms'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalWithdrawalPolicyRouteImport } from './routes/legal/withdrawal-policy'
import { Route as ApiCronRefreshOfferFeedRouteImport } from './routes/api/cron/refresh-offer-feed'
import { Route as AuthenticatedGoQuestKeyStepRouteImport } from './routes/_authenticated/go.$questKey.$step'
import { Route as ApiPublicOfferPostbackOfferIdRouteImport } from './routes/api/public/offer-postback.$offerId'
import { Route as ApiPublicOfferwallSlugRouteImport } from './routes/api/public/offerwall/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeaturedRoute = AuthenticatedFeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersRoute = AuthenticatedOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOfferwallRoute = AuthenticatedOfferwallRouteImport.update({
  id: '/offerwall',
  path: '/offerwall',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferRoute = AuthenticatedReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskRoute = AuthenticatedTaskRouteImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReferralTermsRoute = LegalReferralTermsRouteImport.update({
  id: '/legal/referral-terms',
  path: '/legal/referral-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalWithdrawalPolicyRoute = LegalWithdrawalPolicyRouteImport.update({
  id: '/legal/withdrawal-policy',
  path: '/legal/withdrawal-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRefreshOfferFeedRoute = ApiCronRefreshOfferFeedRouteImport.update({
  id: '/api/cron/refresh-offer-feed',
  path: '/api/cron/refresh-offer-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGoQuestKeyStepRoute =
  AuthenticatedGoQuestKeyStepRouteImport.update({
    id: '/go/$questKey/$step',
    path: '/go/$questKey/$step',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicOfferPostbackOfferIdRoute =
  ApiPublicOfferPostbackOfferIdRouteImport.update({
    id: '/api/public/offer-postback/$offerId',
    path: '/api/public/offer-postback/$offerId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOfferwallSlugRoute = ApiPublicOfferwallSlugRouteImport.update({
  id: '/api/public/offerwall/$slug',
  path: '/api/public/offerwall/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/offerwall': typeof AuthenticatedOfferwallRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/support': typeof AuthenticatedSupportRoute
  '/task': typeof AuthenticatedTaskRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/featured': typeof AuthenticatedFeaturedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/offers': typeof AuthenticatedOffersRoute
  '/offerwall': typeof AuthenticatedOfferwallRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/refer': typeof AuthenticatedReferRoute
  '/support': typeof AuthenticatedSupportRoute
  '/task': typeof AuthenticatedTaskRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/featured': typeof AuthenticatedFeaturedRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/offers': typeof AuthenticatedOffersRoute
  '/_authenticated/offerwall': typeof AuthenticatedOfferwallRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/refer': typeof AuthenticatedReferRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/task': typeof AuthenticatedTaskRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/referral-terms': typeof LegalReferralTermsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/legal/withdrawal-policy': typeof LegalWithdrawalPolicyRoute
  '/api/cron/refresh-offer-feed': typeof ApiCronRefreshOfferFeedRoute
  '/_authenticated/go/$questKey/$step': typeof AuthenticatedGoQuestKeyStepRoute
  '/api/public/offer-postback/$offerId': typeof ApiPublicOfferPostbackOfferIdRoute
  '/api/public/offerwall/$slug': typeof ApiPublicOfferwallSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/featured'
    | '/home'
    | '/notifications'
    | '/offers'
    | '/offerwall'
    | '/onboarding'
    | '/profile'
    | '/refer'
    | '/support'
    | '/task'
    | '/wallet'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/api/cron/refresh-offer-feed'
    | '/go/$questKey/$step'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/featured'
    | '/home'
    | '/notifications'
    | '/offers'
    | '/offerwall'
    | '/onboarding'
    | '/profile'
    | '/refer'
    | '/support'
    | '/task'
    | '/wallet'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/api/cron/refresh-offer-feed'
    | '/go/$questKey/$step'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/featured'
    | '/_authenticated/home'
    | '/_authenticated/notifications'
    | '/_authenticated/offers'
    | '/_authenticated/offerwall'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/refer'
    | '/_authenticated/support'
    | '/_authenticated/task'
    | '/_authenticated/wallet'
    | '/legal/privacy'
    | '/legal/referral-terms'
    | '/legal/terms'
    | '/legal/withdrawal-policy'
    | '/api/cron/refresh-offer-feed'
    | '/_authenticated/go/$questKey/$step'
    | '/api/public/offer-postback/$offerId'
    | '/api/public/offerwall/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalReferralTermsRoute: typeof LegalReferralTermsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalWithdrawalPolicyRoute: typeof LegalWithdrawalPolicyRoute
  ApiCronRefreshOfferFeedRoute: typeof ApiCronRefreshOfferFeedRoute
  ApiPublicOfferPostbackOfferIdRoute: typeof ApiPublicOfferPostbackOfferIdRoute
  ApiPublicOfferwallSlugRoute: typeof ApiPublicOfferwallSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/featured': {
      id: '/_authenticated/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof AuthenticatedFeaturedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers': {
      id: '/_authenticated/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offerwall': {
      id: '/_authenticated/offerwall'
      path: '/offerwall'
      fullPath: '/offerwall'
      preLoaderRoute: typeof AuthenticatedOfferwallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/refer': {
      id: '/_authenticated/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof AuthenticatedReferRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task': {
      id: '/_authenticated/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof AuthenticatedTaskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/referral-terms': {
      id: '/legal/referral-terms'
      path: '/legal/referral-terms'
      fullPath: '/legal/referral-terms'
      preLoaderRoute: typeof LegalReferralTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/withdrawal-policy': {
      id: '/legal/withdrawal-policy'
      path: '/legal/withdrawal-policy'
      fullPath: '/legal/withdrawal-policy'
      preLoaderRoute: typeof LegalWithdrawalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/refresh-offer-feed': {
      id: '/api/cron/refresh-offer-feed'
      path: '/api/cron/refresh-offer-feed'
      fullPath: '/api/cron/refresh-offer-feed'
      preLoaderRoute: typeof ApiCronRefreshOfferFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/go/$questKey/$step': {
      id: '/_authenticated/go/$questKey/$step'
      path: '/go/$questKey/$step'
      fullPath: '/go/$questKey/$step'
      preLoaderRoute: typeof AuthenticatedGoQuestKeyStepRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/offer-postback/$offerId': {
      id: '/api/public/offer-postback/$offerId'
      path: '/api/public/offer-postback/$offerId'
      fullPath: '/api/public/offer-postback/$offerId'
      preLoaderRoute: typeof ApiPublicOfferPostbackOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/offerwall/$slug': {
      id: '/api/public/offerwall/$slug'
      path: '/api/public/offerwall/$slug'
      fullPath: '/api/public/offerwall/$slug'
      preLoaderRoute: typeof ApiPublicOfferwallSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFeaturedRoute: typeof AuthenticatedFeaturedRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOffersRoute: typeof AuthenticatedOffersRoute
  AuthenticatedOfferwallRoute: typeof AuthenticatedOfferwallRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferRoute: typeof AuthenticatedReferRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTaskRoute: typeof AuthenticatedTaskRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedGoQuestKeyStepRoute: typeof AuthenticatedGoQuestKeyStepRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFeaturedRoute: AuthenticatedFeaturedRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOffersRoute: AuthenticatedOffersRoute,
  AuthenticatedOfferwallRoute: AuthenticatedOfferwallRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferRoute: AuthenticatedReferRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTaskRoute: AuthenticatedTaskRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedGoQuestKeyStepRoute: AuthenticatedGoQuestKeyStepRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalReferralTermsRoute: LegalReferralTermsRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalWithdrawalPolicyRoute: LegalWithdrawalPolicyRoute,
  ApiCronRefreshOfferFeedRoute: ApiCronRefreshOfferFeedRoute,
  ApiPublicOfferPostbackOfferIdRoute: ApiPublicOfferPostbackOfferIdRoute,
  ApiPublicOfferwallSlugRoute: ApiPublicOfferwallSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
